FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm","run","start"]


#### Docker build -f Dockerfile.dev .
####  docker run -it -p 3000:3000 CONTAINER_ID



#########
#Volumes 
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image id>

#docker-compose down && docker-compose up --build


####Docker build -f Dockerfile.dev .

